name: Go
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go:
          - "1.22"
          - "1.23"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build & Test
        run: |
          make download-assets
          go test -race -v ./...
        env:
          TZ: Asia/Tokyo # for time.Local
